### ISSUE TITLE
Merge rails-pg-extras-web -> rails-pg-extras

### ISSUE THREAD

**Issue by defkode** [pawurb/rails-pg-extras#12]
@pawurb How about merging repos? In some spare time I could prepare PR. It would be much easier to keep it in sync.

**Comment by pawurb** [comment]
Sounds good. I can also give you an admin rights to my repo if you're interested.

**Comment by matti** [comment]
please make this happen :)

**Comment by pawurb** [comment]
@defkode would you mind me proceeding with the integration myself by doing some copy/paste magic from your repo?

**Comment by defkode** [comment]
Feel free to merge it and adjust!

**Comment by pawurb** [comment]
I've just released 4.0.0 with merged UI. I'll be working on refining it in next versions.
