### ISSUE TITLE
PG::UndefinedFile: ERROR: could not open extensions control file

### ISSUE THREAD

**Issue by kaydee0502** [pawurb/rails-pg-extras#13]
Currently using pg 9.3 and it raises mentioned exception when `RailsPGExtras.add_extentions` is executed..
<img width="1149" alt="Screenshot 2021-11-09 at 4 54 24 PM" src="https://user-images.githubusercontent.com/27851633/140927406-4611fe1e-bcc2-4247-a3d1-7908fd1b79a0.png">

**Comment by pawurb** [comment]
Hi. Can you share the output of:

```
ActiveRecord::Base.connection.execute("SELECT * FROM pg_available_extensions ORDER BY installed_version;").to_a
```

thanks!

**Comment by kaydee0502** [comment]
> Hi. Can you share the output of:
> 
> ```
> ActiveRecord::Base.connection.execute("SELECT * FROM pg_available_extensions ORDER BY installed_version;").to_a
> ```
> 
> thanks!

Hi,

Here's what I got
```
[{"name"=>"plpgsql", "default_version"=>"1.0", "installed_version"=>"1.0", "comment"=>"PL/pgSQL procedural language"}]
```

**Comment by pawurb** [comment]
Hi, please also share the output of:
```
begin; RailsPGExtras.diagnose rescue => e; puts e.backtrace; end
```
