### ISSUE TITLE
Build in UI Dashboard

### ISSUE THREAD

**Issue by CarlosUvaSilva** [pawurb/rails-pg-extras#20]
I'm trying to use the new dashboard in a `api_only = true` Rails app and it seems the UI needs full-fledged app in order to use Views only methods.
I'm getting an error: `undefined method "flash"`

Would it be possible to make this work with an API only app? would be super helpful

Thanks

PS: did some testing and it appears the problem is `if flash[:notice]` inside `views/layouts/rails_pg_extras/web/application.html.erb` if those lines are deleted than it works okay.
would it be possible to check if the `flash` method is available? that would allow us to use this in API mode

**Comment by defkode** [comment]
I was able to reproduce it. @pawurb I will work prepare PR.

**Comment by CarlosUvaSilva** [comment]
@defkode 
it's working great now :+1:

**Comment by pawurb** [comment]
@defkode thanks for a fix! It's been released as 4.4.1
