### ISSUE TITLE
Multiple Databases

### ISSUE THREAD

**Issue by MaicolBen** [pawurb/rails-pg-extras#27]
Thank you for this awesome gem! Can it be used to manage multiple databases (for example: master/replica)?

**Comment by pawurb** [comment]
Hi, awesome to hear you find it useful! I'm afraid currently it is not supported. rails-pg-extras reuses current Rails ActiveRecord connection to a primary database. But the core dependency https://github.com/pawurb/ruby-pg-extras uses a `DATABASE_URL` ENV variable. So, I guess it could be more straightforward to integrate different databases using scripts etc. 

I'll close the issue. Please reopen or just comment if something will still not be clear.
