### ISSUE TITLE
RailsPgExtras.diagnose taking too long and not finishing production.

### ISSUE THREAD

**Issue by coderhs** [pawurb/rails-pg-extras#29]
I ran this gem locally in my system (on my local database) and did give me a lot of insights. I wanted to add it to production and share it with the team. But the `RailsPgExtras.diagnose` is not finsihing (and the web ui is not loading). The production DB is like a 100 GB, comapred to my local DB (for 1 or 2 GB). 

Its been running for over 20 minutes and still not finishing. (Also not sure if its relavent, we have 100s of schema's as well).

**Comment by pawurb** [comment]
Hi. It's strange, the lib normally performs lightweight metadata queries. I guess the only way to debug it is to manually run each check that `diagnose` performs and let me know which one freezes. You'd need to check the [source code](https://github.com/pawurb/ruby-pg-extras/blob/master/lib/ruby_pg_extras/diagnose_data.rb) for that.
