### ISSUE TITLE
Allow to set "public dashboard" via configuration

### ISSUE THREAD

**Issue by morgoth** [pawurb/rails-pg-extras#35]
https://github.com/pawurb/rails-pg-extras/commit/d1a48cb0af58e83f5464e5f1a9632ea49debf260 introduced mandatory authentication

We're having our own authentication in the app, by something like:
```ruby
constraints Constraints::Admin.new do
  mount RailsPgExtras::Web::Engine, at: "pg_extras"
end
```
We don't really want to set `RAILS_PG_EXTRAS_PUBLIC_DASHBOARD` in all the possible apps (using heroku). It would be much easier for us to just set this via gem configuration in the initializer.

**Comment by pawurb** [comment]
I like the idea. Please submit the PR and I'm looking forward to merging it.
