### ISSUE TITLE
Documentation causes error

### ISSUE THREAD

**Issue by c2ofh** [pawurb/rails-pg-extras#41]
Hi,

first of all, awesome Gem! This will help us a lot, to optimize our solution. 
Thank you also for the examples, but some of them are outdated.

There is for example the [Info about Deadlocks](https://pawelurbanek.com/postgresql-fix-performance#deadlocks)
Here you using `RubyPgExtras` instead of `RailsPgExtras`. This causes the Error:

`PG::Error (invalid URI query parameter: "encoding")`

Maybe you can adjust your documentation.

Best.

**Comment by pawurb** [comment]
@c2ofh hi. it looks like gem cannot connect to your database but I cannot tell more without a more detailed trace. Please try to use `RailsPgExtras` instead of `RubyPgExtras` because it reuses Rails db connection. Also double check if your `DATABASE_URL` is correct.
