### ISSUE TITLE
Results for non-public schemas

### ISSUE THREAD

**Issue by drnic** [pawurb/rails-pg-extras#43]
I don't think I'm seeing results for tables outside of `public` schema.

For example, we only have one table in public:

```
# \dt;
            List of relations
 Schema |      Name       | Type  | Owner
--------+-----------------+-------+-------
 public | spatial_ref_sys | table | drnic
```

And lots of tables in other schemas:

```
$ \dt other_schema.*;
    Schema    |                   Name                    |       Type        | Owner
--------------+-------------------------------------------+-------------------+-------
 other_schema | account                                   | table             | drnic
 other_schema | asset                                     | table             | drnic
 other_schema | booking_holds                             | table             | drnic
 ...
 ```
 
 But the various commands, in rake/console/web, only return results for tables in `public`:
 
 
<img width="510" alt="image" src="https://github.com/pawurb/rails-pg-extras/assets/108/a26ca36c-f7cb-43c0-988f-89b5a63cc37e">

Is there a way to configure it to look in an alternate schema, or better, all the schemas in the target database? Thanks 👍

**Comment by drnic** [comment]
Ooh, I found the ruby-pg-extras gem, and figured out I can pass `args: {schema: "other_schema"}` to the various helpers.

```
RailsPgExtras.cache_hit(args: {schema: "other_schema"})
```

I'll create a PR for this for the docs.

**Comment by andyatkinson** [comment]
@pawurb @drnic Hello! For Rideshare, it uses a custom `rideshare` schema. I see I can run this code that @drnic mentioned (and hat tip @danielabaron for noticing this), but is there a way to make this the default via an initializer option? I am digging into the initializer now but didn't immediately see how to set a schema. I did configure an ENV var for rails-pg-extras. Unfortunately even though the default schema for the PostgreSQL user I'm connecting as (which is `rideshare`) wasn't used, and `public` was still used. I've removed the `public` schema from that application database following "Safe schema patterns" best practices.

Expected: The default schema for the PostgreSQL user is used. I've removed 
Actual: Queries use the `public` schema when running `bin/rails pg_extras:cache_hit` regardless of user's default schema

```sh
bin/rails runner 'RailsPgExtras.table_cache_hit(args: { schema: "rideshare" })'
```

**Comment by pawurb** [comment]
@andyatkinson thanks for pointing out. I've added a way to specify default schema via ENV here: https://github.com/pawurb/ruby-pg-extras/commit/43f2d2b2fa5d76e10b113ecc9c41b603ecd81a9b it's now out as `5.3.1`. Please confirm if it resolves the issue.

**Comment by andyatkinson** [comment]
Hi @pawurb Nice, that fixes it. Here's my sample app for the book with a PR related to this gem update, and then invocations of the commands with the updated gem version:
https://github.com/andyatkinson/rideshare/pull/162

I had hoped I could add the ENV var to the `.env` file and it would "just work", but that wasn't the case. I imagine that would need some more work? Setting the env var in the terminal though before I invoke the commands works fine.

This fixes it for `diagnose` too, we can see the schema is included in the generated SQL queries. Here's an example:

```sql
SELECT
....
FROM pg_stat_user_indexes ui
....
AND schemaname = 'rideshare'
...
```

Thanks!
