### ISSUE TITLE
Diagnose does not accept args options like elsewhere

### ISSUE THREAD

**Issue by andyatkinson** [pawurb/rails-pg-extras#46]
Since I could run:

```sh
bin/rails runner 'RailsPgExtras.table_cache_hit(args: { schema: "rideshare" })'
```

to check the table_cache_hit rate, I thought I could do something similar for diagnose, specifying a custom schema, but that's not supported:

```sh
bin/rails runner 'RailsPgExtras.diagnose(args: { schema: "rideshare" })'

....
rails-pg-extras-5.3.0/lib/rails-pg-extras.rb:53:in `diagnose': unknown keyword: :args (ArgumentError)
        from /Users/andy/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails/commands/runner/runner_command.rb:46
...
```

Apologies if I missed this since I admittedly didn't dig into this deeply, but I know for system catalogs we might not need to set a schema, but for custom schemas used with apps, where tables are located, presumably diagnose needs to access those, and we'd need to set a schema to be included in SQL queries? I'll keep playing around with this a bit but wanted to bring it up early before I forgot.

Update:

Related: https://github.com/pawurb/rails-pg-extras/issues/43#issuecomment-1854730076

**Comment by pawurb** [comment]
Diagnose is not a one off query but has a more complex logic. I think that setting default schema via ENV added in `5.3.1` should resolve it. If not it would require some rewrite of `RubyPgExtras::DiagnoseData` for it to accept args. I currently don't have time to look into it but PRs are always welcome.

**Comment by andyatkinson** [comment]
Thanks @pawurb I'll take a look into `RubyPgExtras::DiagnoseData`. I didn't really see where the queries were on initial glance (only had a few minutes to look).
