### ISSUE TITLE
ActiveRecord::StatementInvalid when pg_stat_statements is enabled

### ISSUE THREAD

**Issue by maxrosecollins** [pawurb/rails-pg-extras#5]
pg_stat_statements is enabled

I can see the following when I run `RailsPGExtras.extensions`

`pg_stat_statements | 1.7             |                   | track execution statistics of all SQL statements executed`

When I run ` RailsPGExtras.calls`

I get the following error

```
Traceback (most recent call last):
        1: from (irb):14
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "pg_stat_statements" does not exist)
LINE 8: FROM pg_stat_statements WHERE userid = (SELECT usesysid FROM
```

**Comment by pawurb** [comment]
Hi @maxrosecollins it looks like the extension is available but not installed. You should get:

`| pg_stat_statements  | 1.7  | 1.7 | track execution statistics of all SQL statements executed |`

Notice two version numbers not single one like you get. You should double check the docs on how to enable the extension in your database setup.

**Comment by maxrosecollins** [comment]
Hi @pawurb 

I have `shared_preload_libraries = 'pg_stat_statements'` in my `postgresql.conf`

I looks like I had to run `CREATE EXTENSION pg_stat_statements;` to get it working 🤷‍♂️
